// generated by "sampctl package init"
#include <a_samp>
#include <util>
#include <env>
#include <strlib>
#include <a_mysql>

#define YSI_NO_HEAP_MALLOC

#include <YSI_Data\y_hashmap>
#include <YSI_Data\y_iterate>
#include <YSI_Coding/y_inline>
#include <YSI_Coding/y_va>
#include <YSI_Extra\y_inline_mysql>

#include <mysql_prepared>
#include <sscanf2>
#include <Pawn.CMD>
#include <mdialog>

/*===============================[config]=============================== */
#include "src\config\config_import.pwn"
#include "src\vehicle\vehicle_import.pwn"
#include "src\dealership\dealership_import.pwn"

main() {

}

